package com.soupmodmaker.core.codegen;

import com.soupmodmaker.core.workspace.WorkspaceElement;
import com.soupmodmaker.core.workspace.elements.ItemElement;

/**
 * Simple code generator for items.
 * Demonstrates clean code generation without templates (proof of concept).
 */
public class SimpleItemGenerator implements CodeGenerator {

    @Override
    public GeneratedCode generate(WorkspaceElement element, CodeContext context) {
        if (!(element instanceof ItemElement)) {
            throw new IllegalArgumentException("Element must be an ItemElement");
        }

        ItemElement item = (ItemElement) element;

        // Generate class name (e.g., ruby -> ItemRuby)
        String className = "Item" + capitalize(item.getId());

        // Get package info from context
        String basePackage = context.getJavaPackage();
        String packageName = basePackage + ".item";

        // Generate clean Java code
        String code = generateItemCode(className, packageName, item);

        // Calculate file path
        String filePath = packageName.replace('.', '/') + "/" + className + ".java";

        return new GeneratedCode(className, packageName, code, filePath);
    }

    @Override
    public boolean supports(String elementType) {
        return "item".equals(elementType);
    }

    /**
     * Generate clean, readable Java code for an item.
     * This is the key differentiator from MCreator - clean code!
     */
    private String generateItemCode(String className, String packageName, ItemElement item) {
        StringBuilder code = new StringBuilder();

        // Package declaration
        code.append("package ").append(packageName).append(";\n\n");

        // Imports
        code.append("import net.minecraft.item.Item;\n");
        code.append("import net.minecraft.creativetab.CreativeTabs;\n\n");

        // Class documentation
        code.append("/**\n");
        code.append(" * ").append(item.getName()).append("\n");
        code.append(" * Auto-generated by SoupModMaker2\n");
        code.append(" */\n");

        // Class declaration
        code.append("public class ").append(className).append(" extends Item {\n\n");

        // Constructor
        code.append("    public ").append(className).append("() {\n");
        code.append("        super();\n");
        code.append("        this.setUnlocalizedName(\"").append(item.getId()).append("\");\n");
        code.append("        this.setRegistryName(\"").append(item.getId()).append("\");\n");
        code.append("        this.setCreativeTab(CreativeTabs.MATERIALS);\n");

        // Max stack size
        if (item.getMaxStackSize() != 64) {
            code.append("        this.setMaxStackSize(").append(item.getMaxStackSize()).append(");\n");
        }

        code.append("    }\n");

        // Close class
        code.append("}\n");

        return code.toString();
    }

    /**
     * Capitalize first letter of a string.
     */
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }
}
