package ${package}.item;

import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

/**
 * Item registry for ${modName}
 * Generated by SoupModMaker2
 */
@Mod.EventBusSubscriber
public class ${modId?cap_first}Items {

<#list items as item>
    public static final Item ${item.id?upper_case} = new ${item.className}();
</#list>

    public static void register() {
        // Items are registered via the event handler
    }

    @SubscribeEvent
    public static void registerItems(RegistryEvent.Register<Item> event) {
<#list items as item>
        event.getRegistry().register(${item.id?upper_case});
</#list>
    }
}
