package ${package}.item;

import net.minecraft.item.Item;
import net.minecraft.creativetab.CreativeTabs;

/**
 * ${itemName}
 * Generated by SoupModMaker2
 */
public class ${className} extends Item {

    public ${className}() {
        super();
        this.setUnlocalizedName("${itemId}");
        this.setRegistryName("${itemId}");
        this.setCreativeTab(CreativeTabs.MATERIALS);
<#if maxStackSize != 64>
        this.setMaxStackSize(${maxStackSize});
</#if>
    }
}
