package ${package};

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import org.apache.logging.log4j.Logger;

/**
 * ${modName}
 * Generated by SoupModMaker2
 *
 * @author ${author}
 */
@Mod(modid = ${className}.MODID, name = ${className}.NAME, version = ${className}.VERSION)
public class ${className} {

    public static final String MODID = "${modId}";
    public static final String NAME = "${modName}";
    public static final String VERSION = "${version}";

    private static Logger logger;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();
        logger.info("${modName} is loading...");

        // Register items
        ${modId?cap_first}Items.register();
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        logger.info("${modName} initialization complete");
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        logger.info("${modName} post-initialization complete");
    }
}
