[
  {
    "modid": "${modId}",
    "name": "${modName}",
    "description": "${description}",
    "version": "${version}",
    "mcversion": "1.12.2",
    "url": "",
    "updateUrl": "",
    "authorList": ["${author}"],
    "credits": "Generated by SoupModMaker2",
    "logoFile": "",
    "screenshots": [],
    "dependencies": []
  }
]
