# ${modName}

Generated by SoupModMaker2

## Building

This mod is for **Minecraft 1.12.2** using **Forge**.

### Requirements

- Java 8 (JDK 1.8)
- The mod uses Gradle 4.10.3 (included via wrapper)

### Build Instructions

```bash
# Windows
gradlew.bat build

# macOS/Linux
./gradlew build
```

The built mod JAR will be in: `build/libs/${modId}-${version}.jar`

### Running in Development

```bash
# Run Minecraft client
./gradlew runClient

# Run Minecraft server
./gradlew runServer
```

### Installing the Mod

1. Build the mod (see above)
2. Copy `build/libs/${modId}-${version}.jar` to your Minecraft `mods/` folder
3. Run Minecraft 1.12.2 with Forge installed

### Note About Gradle Version

**Important:** This mod requires Gradle 4.10.3 (not the latest Gradle 9.x).

The included `gradlew` wrapper will automatically use the correct version.
**Always use `./gradlew` (or `gradlew.bat`) - don't use your system's `gradle` command!**

## Mod Information

- **Mod ID:** ${modId}
- **Version:** ${version}
- **Minecraft Version:** 1.12.2
- **Forge Version:** 14.23.5.2859
- **Author:** ${author}

## Description

${description}

---

**Generated by SoupModMaker2** - https://github.com/GuyThatLivesAndCodes/SoupModMaker2
